name: du
description: Runs du to determine the size of the input file in KB
tools:
  - du:
      description: Estimates file space usage
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input_file:
      type: file
      description: The file to determine the size of.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - size:
      type: string
      description: The size of the file in KB
authors:
  - "@marc-jones"