name: clipqc
description: Generate CLIP-Seq specific statistics
keywords:
  - QC
tools:
  - pybedtools:
      description: |
        The BEDTools suite of programs is widely used for genomic interval manipulation or "genome algebra".
        pybedtools wraps and extends BEDTools and offers feature-level manipulations from within Python.
      homepage: https://github.com/daler/pybedtools
      documentation: http://daler.github.io/pybedtools
      licence: ["MIT"]
input:
  - premap:
      type: file
      description: Log files from Bowtie alignment
  - mapped:
      type: file
      description: Log files from STAR alignment
  - dedup:
      type: file
      description: Log files from UMITools dedup
  - xlinks:
      type: bed
      description: Crosslink positions and cDNA scores
  - icount:
      type: bed
      description: Peaks called by iCount
  - paraclu:
      type: bed
      description: Peaks called by paraclu
  - clippy:
      type: bed
      description: Peaks called by Clippy
output:
  - log:
      type: file
      description: Files containing statistics on the input samples
      pattern: "*.tsv"
authors:
  - "@amchakra"
  - "@marc-jones"
