name: get_crosslinks
description: TODO
tools:
  - bedtools:
    description: Fast, flexible toolset for genome arithmetic.
    homepage: https://bedtools.readthedocs.io/en/latest/
    documentation: https://bedtools.readthedocs.io/en/latest/
    licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: TODO
  - bai:
      type: file
      description: TODO
  - fai:
      type: file
      description: TODO
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - crosslinkBed:
      type: file
      description: TODO
      pattern: "*bed.gz"
authors:
  - "@CharlotteAnne"