name: find_longest_transcript
description: |
  TODO
tools:
  - gawk:
      description: |
        Flexible and powerful data analysis / manipulation library for Python,
        providing labeled data structures similar to R data.frame objects,
        statistical functions, and much more.
      homepage: https://www.gnu.org/software/gawk/
      documentation: https://www.gnu.org/software/gawk/manual/
      licence: ["GNU"]
input:
  - gtf:
      type: file
      description: TODO
output:
  - longest_transcript:
      type: file
      description: TODO
      pattern: "longest_transcript.txt"
  - transcriptome_index:
      type: file
      description: TODO
      pattern: "transcriptome_index.fa.fai"
authors:
  - "@rfara"