name: filter_transcriptome_bam
description: TODO
tools:
  - samtools:
      description: Tools for manipulating next-generation sequencing data
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/
      licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - transcriptome_bam:
      type: file
      description: TODO
  - transcripts:
      type: file
      description: TODO
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - filtered_bam:
      type: file
      description: TODO
      pattern: "*transcriptome.bam"
authors:
  - "@rfara"