name: umicollapse
description: Deduplicate reads based on the mapping co-ordinate and the UMI attached to the read.
keywords:
  - umicollapse
  - deduplication
tools:
  - umicollapse:
      description: >
        UMICollapse contains tools for dealing with Unique Molecular Identifiers (UMIs)/Random Molecular Tags (RMTs).
      documentation: https://github.com/Daniel-Liu-c0deb0t/UMICollapse
      license: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: |
        BAM file containing reads to be deduplicated via UMIs.
      pattern: "*.{bam}"
  - bai:
      type: file
      description: |
        BAM index files corresponding to the input BAM file.
      pattern: "*.{bai}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file with deduplicated UMIs.
      pattern: "*.{bam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@Daniel-Liu-c0deb0t"
  - "@CharlotteAnne"
