name: icount_rnamaps
description: Computes distribution of cross-links relative to genomic landmarks.
keywords:
  - iCLIP
tools:
  - icount:
      description: Computational pipeline for analysis of iCLIP data
      homepage: https://icount.readthedocs.io/en/latest/
      documentation: https://icount.readthedocs.io/en/latest/
      licence: ['MIT']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: BED file of crosslinks
  - regions:
      type: file
      description: An iCount regions file
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - rnamaps:
      type: file
      description: TODO
      pattern: "rnamaps*"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.yml}"
authors:
  - "@marc-jones"